name: Playwright Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install Allure commandline
        run: npm install -g allure-commandline

      - name: Run Playwright tests
        run: npm run test

      - name: Upload Allure results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: ./allure-results

      - name: Generate Allure Report
        run: |
          allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      - name: Send notification to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: "OIS Automation"
          SLACK_ICON_EMOJI: ":rocket:"
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: "Playwright Test Run — ${{ job.status == 'success' && '✅ PASSED' || '❌ FAILED' }}"
          SLACK_MESSAGE: |
            SLACK_MESSAGE: |
              *Repository:* ${{ github.repository }}
              *Branch:* ${{ github.ref_name }}
              *Commit:* <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>
              *Author:* ${{ github.actor }}
              *Workflow:* <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>
              *Allure Report:* <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Download Allure artifacts>
