name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Test environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Set environment variable
        run: |
          if [ -z "${{ github.event.inputs.environment }}" ]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          fi

      - name: Install Allure commandline
        run: npm install -g allure-commandline

      - name: Run Playwright tests
        run: npm run test

      - name: Upload Allure results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: ./allure-results

      - name: Generate Allure Report
        run: |
          allure generate ./allure-results --clean -o ./allure-report-${{ env.ENVIRONMENT }}

      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ env.ENVIRONMENT }}
          path: ./allure-report-${{ env.ENVIRONMENT }}

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report-${{ env.ENVIRONMENT }}
          destination_dir: ${{ env.ENVIRONMENT }}

      - name: Send notification to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: "OIS Automation"
          SLACK_ICON_EMOJI: ":rocket:"
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: "Test Run — ${{ job.status == 'success' && '✅ PASSED' || '❌ FAILED' }}"
          SLACK_FOOTER: ""
          SLACK_LINK_NAMES: "false"
          SLACK_UNFURL_LINKS: "false"
          SLACK_MESSAGE: |
            *Event:* ${{ github.event_name == 'workflow_dispatch' && 'Manual Trigger' || github.event_name == 'schedule' && 'Scheduled Run' || github.event_name == 'push' && 'Push to Main Branch' || github.event_name }}
            *Environment:* ${{ env.ENVIRONMENT }}
            *Author:* ${{ github.actor }}
            *Workflow:* <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>
            *Allure Report:* <https://skvortsov1.github.io/OIS-auto/${{ env.ENVIRONMENT }}/index.html|Open Allure Report>
